### ISSUE TITLE
Permission Denied while running sample call.js

### ISSUE THREAD

**Issue by txrubel** [fonoster/fonoster#236] opened 2021-11-17 00:19 UTC
Hello,

I am very new on this project. Just trying to follow this doc, https://learn.fonoster.com/docs/getting_started/create_a_voice_application and bring up a simple call test. I have created a project, provider, and number.

I have created call.js as describe here, https://learn.fonoster.com/docs/getting_started/make_an_outbound_call

but getting following error while we run node call.js

![image](https://user-images.githubusercontent.com/38957915/142086648-8e036aee-56df-4005-a750-1aa062faf03f.png)

I have no idea is there anything wrong I have done, please help me to find the issue.

Thanks,
Salah

**Comment by psanders** [comment] 2021-11-17 01:19
Hi @txrubel 

It is likely that you are using your User Account credentials, instead of the [Project Credentials](https://learn.fonoster.com/docs/getting_started/create_a_project). 

Consider opening a feature request asking for a better error (perhaps we should include examples of why the permission error).

Anyways. I'm closing this since it's not a bug or a feature request. But feel free to continue on our [Github Discussion](https://github.com/fonoster/fonoster/discussions/209) which is more appropriate for questions 🙂

**Closed as completed by psanders** 2021-11-17 01:19 UTC
