### ISSUE TITLE
Memory leak in Rox AI due to excessive use of require

### ISSUE THREAD

**Issue by psanders** [fonoster/fonoster#262] opened 2022-01-20 02:38 UTC
**Describe the bug**

The voice application module, [Rox](https://github.com/fonoster/rox/blob/7899860e7ef4c259f3eb92a9af5759f670fd8c12/src/intents/dialogflow_es.ts#L34), reads the configuration file for every call which causes a memory leake.

**To Reproduce**

See the relevant code [here](https://github.com/fonoster/rox/blob/7899860e7ef4c259f3eb92a9af5759f670fd8c12/src/intents/dialogflow_es.ts#L34)  

**Expected behavior**

The configuration should be loaded only at on start.

**Screenshots**

**System information (please complete the following):**
 - OS: All
 - NodeJS, NPM versions: All
 - CTL version at until 0.0.13
  
**Additional context**

NA

**Comment by efraa** [comment] 2022-01-20 15:06
🙉

**Comment by BrayanMnz** [comment] 2022-05-10 04:31
The issue is now replicated on my local... I can see the memory of the running program, increasing every time a new call is being made.

I'll self-assign it to me and work in the solution later.

Update : 

I saw it's already assigned to you @psanders, Are u working on it ?

**Comment by psanders** [comment] 2022-05-11 11:52
I can use some help with this one. You got it.

**Comment by efraa** [comment] 2023-01-25 15:28
@psanders This issue was solved here: 

https://github.com/fonoster/rox/commit/957951efe6d54cf1b6893388213c9ae3efaa5270#diff-a495a1b2884e88ccde24d73816611e44195feefbe78f246446e97bb2434d17a2

**Comment by efraa** [comment] 2023-01-25 19:27
Closing this issue, it was fixed a few months ago.

**Closed as completed by efraa** 2023-01-25 19:27 UTC
Labels: bug, voice

**Comment by psanders** [comment] 2023-01-25 21:06
Perfect. Thanks.
